version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - frontend:/usr/share/nginx/html/frontend
      - ./nginx/cert:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "443:443"

  frontend:
   container_name: frontend
   build:
     context: ./frontend
     dockerfile: Dockerfile
   volumes:
     - frontend:/app/dist

volumes:
  frontend:
