version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - frontend:/usr/share/nginx/html/frontend
      - ${SSL_CERT_PATH}:/etc/nginx/certs/cert.pem
      - ${SSL_CERT_KEY_PATH}:/etc/nginx/certs/key.pem
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
    command: /bin/bash -c "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - frontend:/app/dist

volumes:
  frontend:
